### ISSUE TITLE
uh oh

### ISSUE THREAD

**Issue by darkdarcool** [RayhanADev/The-Scariest-Snek-Program#1]
Me: Downloads and runs it on my computers terminal.

Computer: Hmm, only one file, but idk about this

Me: pypy3 main.py

Computer: uh o(computer static)

Computer: (crash)

**Comment by RayhanADev** [comment]
# Yes

**Comment by darkdarcool** [comment]
my computer is now going to therapy

**Comment by RayhanADev** [comment]
Lol

**Comment by darkdarcool** [comment]
compter to therapist: it all happened so fast, I just don't think I can be a computer anymore
